### ISSUE TITLE
Abiilty to get TaggedValue by KeyPath

### ISSUE THREAD

**Issue by 50kudos** [microsoft/elm-json-tree-view#5]
Hi, this is a nice package. Does it make sense to add this function?:
```elm
taggedValue : KeyPath -> Node -> TaggedValue
```
Pros: Decouple to the `viewScalar`
Cons: Require another walking `Node` since `viewNodeInternal` ties to Html

Or
```elm
type alias Config msg =
    { onSelect : Maybe ((KeyPath, TaggedValue) -> msg)
    , toMsg : State -> msg
    }
``` 
Pros: Easy to add [here](https://github.com/Microsoft/elm-json-tree-view/blob/2.0.0/src/JsonTree.elm#L329).
Cons: Breaking change although it's painless to upgrade, just modifying a msg

Thanks!

**Comment by klazuka** [comment]
It totally makes sense. In fact, this package was extracted from a larger piece of software which includes that functionality along with a Json.Decode-style API for data extraction. The only reason I left it out was that I wanted to keep it simple and see what people needed. I’ll consider adding it.

**Comment by 50kudos** [comment]
It's definitely fine to discard this little function. It would be nice if you could share something similar to the following function:

```elm
taggedValue : JsonTree.KeyPath -> JsonTree.Node -> Maybe JsonTree.TaggedValue
taggedValue keyPath node =
    if String.isEmpty keyPath then
        Just node.value

    else
        case node.value of
            JsonTree.TList nodeList ->
                nodeList
                    |> List.filter (\a -> String.startsWith a.keyPath keyPath)
                    |> List.head
                    |> Maybe.andThen (taggedValue keyPath)

            JsonTree.TDict nodeDict ->
                Dict.values nodeDict
                    |> List.filter (\a -> String.startsWith a.keyPath keyPath)
                    |> List.head
                    |> Maybe.andThen (taggedValue keyPath)

            value ->
                if node.keyPath == keyPath then
                    Just value

                else
                    Nothing
```

**Comment by 50kudos** [comment]
Closed for sanity. Keep it simple. 🍨

**Comment by klazuka** [comment]
I'll leave this open as it's a good idea.

**Comment by klazuka** [comment]
Moved to https://github.com/klazuka/elm-json-tree-view/issues/1
