### ISSUE TITLE
Corrupt zip when downloading package

### ISSUE THREAD

**Issue by mostlyobvious** [microsoft/elm-json-tree-view#7]
Hey, I've just noticed on [CI](https://circleci.com/gh/RailsEventStore/rails_event_store/18771) that my elm builds are suddenly failing on the following:

```
Starting downloads...

  ✗ Microsoft/elm-json-tree-view 2.0.0

-- CORRUPT ZIP -----------------------------------------------------------------

I got an unexpected zip file from:

    <https://github.com/Microsoft/elm-json-tree-view/zipball/2.0.0/>

I check the hash the zip, and it seems off:

  Expected: 6e84a645c3c871ea742506eb1c9352c2a1b04b18
    Actual: 2c6f4a6d554f9a95807ae02b0a52260389c196f4

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
```

I've reproduced this on dev machine (after getting rid of `~/.elm`). 

Any ideas what caused the trouble?

**Comment by peterszerzo** [comment]
Looks like this has to do with the organization name being changed from `Microsoft` to `microsoft`, because apparently `elm package` does not follow http redirects (I talked to Evan about this at some point, though not sure how things look these days).

**Comment by mostlyobvious** [comment]
> Looks like this has to do with the organization name being changed from Microsoft to microsoft

Thanks! Your workaround helped me move forward, I appreciate.

**Comment by peterszerzo** [comment]
I should say what the workaround is: I published my fork under https://package.elm-lang.org/packages/peterszerzo/elm-json-tree-view/latest/. I explained why the fork was necessary in the readme of https://github.com/peterszerzo/elm-json-tree-view.

**Comment by klazuka** [comment]
I will probably just re-publish under the new name and deprecate the old one. It seems like a better option than waiting for a fix in elm-package.

**Comment by klazuka** [comment]
I re-published under my personal account: https://github.com/klazuka/elm-json-tree-view.

All future work will be done under 'klazuka' instead of 'microsoft'.
